[pytest]

testpath =tests
python_functions =test_*
addopts =
     -v
     --html=reports/report.html
     --self-contained-html
markers =
   smoke:Mark test as smoke
   regression: Mark test as regression
